name: FJetpack
main: me.phantomxcraft.FJetpack
description: Simple and Customizable a Jetpack Plugin
version: 0.2.5
api-version: 1.13
author: PhantomXCraft
softdepend: [CMI]
commands:
  fjetpack:
    aliases: [fj]
    description: Main FJetpack command.
permissions:
  fjetpack.admin:
    description: Allows use of all FJetpack commands.
    default: op
    children:
      fjetpack.help: true
      fjetpack.reload: true
      fjetpack.get: true
      fjetpack.checkupdate: true
  fjetpack.help:
    default: true
  fjetpack.reload:
    default: false
  fjetpack.get:
    default: false
  fjetpack.checkupdate:
    default: false